[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v

[coverage:run]
source = src
omit =
    */site-packages/*
    */__pycache__/*

[coverage:report]
precision = 2
show_missing = True
